modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/allurement/issues"
license = "https://github.com/team-abnormals/allurement/blob/main/LICENSE.txt"

[[mods]]
    modId = "allurement"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg"
    displayName = "Allurement"
    description = '''
    Template description.
    '''

[[dependencies.allurement]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.allurement]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.allurement]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.0.5,)"
    ordering = "AFTER"
    side = "BOTH"