modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/allurement/issues"
license = "https://github.com/team-abnormals/allurement/blob/main/LICENSE.txt"

[[mods]]
    modId = "allurement"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:enchanted_book"
    configBackground = "minecraft:textures/block/obsidian.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five"
    displayURL = "https://www.teamabnormals.com/mods/allurement"
    displayName = "Allurement"
    description = '''
    Allurement adds a selection of new enchantments to help diversify gear later in the game.
    Also included are some experience and enchanting tweaks, such as allowing for enchanting horse armor.
    '''

[[dependencies.allurement]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.allurement]]
    modId = "forge"
    mandatory = true
    versionRange = "[39.0.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.allurement]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[5.0.0,)"
    ordering = "AFTER"
    side = "BOTH"