modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/allurement/issues"
license = "https://github.com/team-abnormals/allurement/blob/main/LICENSE.txt"

[[mods]]
    modId = "allurement"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five"
    displayName = "Allurement"
    description = '''
    Allurement adds a selection of new enchantments to help diversify gear later in the game.
    Also included are some experience and enchanting tweaks, such as allowing for enchanting horse armor.
    '''

[[dependencies.allurement]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.allurement]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.0.14,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.allurement]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.0.5,)"
    ordering = "AFTER"
    side = "BOTH"